atualizando dockerfiles

diff --git a/images/php-fpm/Dockerfile b/images/php-fpm/Dockerfile
--- a/images/php-fpm/Dockerfile
+++ b/images/php-fpm/Dockerfile
@@ -4,19 +4,62 @@ MAINTAINER  Agnaldo Marinho "agnaldoneto@ufpa.br"
 
 COPY sources.list /etc/apt/sources.list
 
-RUN apt-get update; apt-get -y install php php-fpm php-cli php-mcrypt php-intl php-mysql php-curl php-gd php-soap php-xml php-zip php-readline php-opcache php-json php-gd 
+RUN apt-get update; apt-get -y install php php-fpm php-cli php-mcrypt php-intl php-mysql php-curl php-gd php-soap php-xml php-zip php-readline php-opcache php-json php-gd
 
 RUN rm -rf /var/lib/apt/lists/*
+
+COPY  docker-php-entrypoint.sh /usr/local/bin/docker-php-entrypoint.sh
+RUN chmod +x /usr/local/bin/docker-php-entrypoint.sh
+
+ENTRYPOINT ["docker-php-entrypoint"]
 
 RUN sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/7.0/fpm/php-fpm.conf 
 RUN sed -i 's/;extension=mysql.so/extension=mysql.so/g' /etc/php/7.0/fpm/php.ini
 RUN sed -i 's/;extension=pdo_mysql.so/extension=pdo_mysql.so/g' /etc/php/7.0/fpm/php.ini
 
+RUN set -ex \
+    && cd /usr/local/etc \
+    && if [ -d php-fpm.d ]; then \
+        # for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
+        sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
+        cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+    else \
+        # PHP 5.x doesn't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
+        mkdir php-fpm.d; \
+        cp php-fpm.conf.default php-fpm.d/www.conf; \
+        { \
+            echo '[global]'; \
+            echo 'include=etc/php-fpm.d/*.conf'; \
+        } | tee php-fpm.conf; \
+    fi \
+    && { \
+        echo '[global]'; \
+        echo 'error_log = /proc/self/fd/2'; \
+        echo; \
+        echo '[www]'; \
+        echo '; if we send this to /proc/self/fd/1, it never appears'; \
+        echo 'access.log = /proc/self/fd/2'; \
+        echo; \
+        echo 'clear_env = no'; \
+        echo; \
+        echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+        echo 'catch_workers_output = yes'; \
+    } | tee php-fpm.d/docker.conf \
+    && { \
+        echo '[global]'; \
+        echo 'daemonize = no'; \
+        echo; \
+        echo '[www]'; \
+        echo 'listen = [::]:9000'; \
+    } | tee php-fpm.d/zz-docker.conf
+
 RUN usermod -u 1000 www-data
+
+WORKDIR /var/www/html
 
 EXPOSE 9000
 
-CMD ["php-fpm7.0", "-F"]
+CMD ["php-fpm"]
 
 
 
